### ISSUE TITLE
syncing stuck

### ISSUE THREAD

**Issue by rohit12043-zz** [SuperiorOS/manifest#1]
while syncing,it is stuck at 
Fetching project platform/external/libavc
Fetching project platform/external/drm_hwcomposer
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0        
Fetching projects:  97% (662/682)  remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0        
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0        
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0        
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0        
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0        
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0        
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0        
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0        
Fetching projects:  98% (669/682)  remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0        
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0        
Fetching project android_hardware_qcom_audio
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0        
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0        
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0        
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0        
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0        
Fetching projects:  99% (676/682)  Fetching project android_hardware_qcom_media
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0        
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0        
Fetching project android_hardware_qcom_media
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0

**Comment by Sweeto143** [comment]
No problem at all ..

Check this - [https://imgur.com/a/ZUgrEqN](url)

**Comment by Darkstar085** [comment]
Nothing like this..

Check this :- https://ibb.co/3F662Tp
