### ISSUE TITLE
How to merge and update the Superior OS thirteen branch to the latest Android 13 release

### ISSUE THREAD

**Issue by VTVishwanath** [SuperiorOS/manifest#20]
How to merge and update the Superior OS thirteen branch to the latest Android 13 release?

I want to merge the latest release https://android.googlesource.com/platform/manifest/+/refs/heads/android-13.0.0_r83 of android with the SuperiorOS thirteen. Is there any documentation to do the same.

I need some steps/instructions to do the same.

**Comment by Darkstar085** [comment]
Merge from there..
