### ISSUE TITLE
package "android/soong/generator" already has a package context

### ISSUE THREAD

**Issue by jbcaaa** [SuperiorOS/manifest#21]
Any idea how to resolve this? Searched everywhere on the internet still can't find anything

`[ 98% 411/416] converting Android.bp files to BUILD files at /home/jbcaaa/SuperiorOS/out/soong/bp2build
FAILED: /home/jbcaaa/SuperiorOS/out/soong/bp2build_files_marker
cd "$(dirname "/home/jbcaaa/SuperiorOS/out/host/linux-x86/bin/soong_build")" && BUILDER="$PWD/$(basename "/home/jbcaaa/SuperiorOS/out/host/linux-x86/bin/soong_build")" && cd / && env -i  "$BUILDER"     --top "$TOP"     --soong_out "/home/jbcaaa/SuperiorOS/out/soong"     --out "/home/jbcaaa/SuperiorOS/out"     --bp2build_marker /home/jbcaaa/SuperiorOS/out/soong/bp2build_files_marker --globListDir bp2build_files --globFile /home/jbcaaa/SuperiorOS/out/soong/globs-bp2build_files.ninja -t -l /home/jbcaaa/SuperiorOS/out/.module_paths/Android.bp.list --available_env /home/jbcaaa/SuperiorOS/out/soong/soong.environment.available --used_env /home/jbcaaa/SuperiorOS/out/soong/soong.environment.used.bp2build_files Android.bp
panic: package "android/soong/generator" already has a package context

goroutine 1 [running]:
github.com/google/blueprint.NewPackageContext({0x11d0d0f, 0x17})
        /home/jbcaaa/SuperiorOS/build/blueprint/package_ctx.go:100 +0x36e
android/soong/android.NewPackageContext(...)
        /home/jbcaaa/SuperiorOS/build/soong/android/package_ctx.go:34
superior/soong/generator.init()
        /home/jbcaaa/SuperiorOS/vendor/superior/build/soong/generator/generator.go:39 +0x25
18:33:34 soong bootstrap failed with: exit status 1
ninja: build stopped: subcommand failed.

#### failed to build some targets (05:18 (mm:ss)) ####`

**Comment by jbcaaa** [comment]
my manifest: SuperiorOS android14
my system: Arch Linux
my devicetree: phh( switch to another dt cannot solve the problem)

**Comment by Darkstar085** [comment]
Force sync & try..

**Comment by jbcaaa** [comment]
> Force sync & try..

Well, it doesn't work.

**Comment by Darkstar085** [comment]
Then no idea
