### ISSUE TITLE
I met two problem while building superioros 13

### ISSUE THREAD

**Issue by jbcaaa** [SuperiorOS/manifest#22]
I met two problem while building superioros 13

one is

error: invalid file path 'packages/apps/Settings/res/values/superior_strings.xml.orig'.

and the other is

The failing command was run inside an sbox sandbox in temporary directory
/home/jbcaaa/android-superior/out/soong/.temp/sbox/ec4da9e1e541952516e84dd81c781a52d32eae3b
The failing command line can be found in
/home/jbcaaa/android-superior/out/soong/.temp/sbox/ec4da9e1e541952516e84dd81c781a52d32eae3b/sbox_command.0.bash
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space

Any way to solve them? I searched the whole Internet but didn't find anything.

**Comment by Darkstar085** [comment]
There is no error in source.. check ur build machine..
