### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by samrth012** [SuperiorOS/manifest#26]
FAILED: /home/lucifer/roms-14/sup-ext/out/soong/bp2build_files_marker
cd "$(dirname "/home/lucifer/roms-14/sup-ext/out/host/linux-x86/bin/soong_build")" && BUILDER="$PWD/$(basename "/home/lucifer/roms-14/sup-ext/out/host/linux-x86/bin/soong_build")" && cd / && env -i  "$BUILDER"     --top "$TOP"     --soong_out "/home/lucifer/roms-14/sup-ext/out/soong"     --out "/home/lucifer/roms-14/sup-ext/out"     --bp2build_marker /home/lucifer/roms-14/sup-ext/out/soong/bp2build_files_marker --globListDir bp2build_files --globFile /home/lucifer/roms-14/sup-ext/out/soong/globs-bp2build_files.ninja -t -l /home/lucifer/roms-14/sup-ext/out/.module_paths/Android.bp.list --available_env /home/lucifer/roms-14/sup-ext/out/soong/soong.environment.available --used_env /home/lucifer/roms-14/sup-ext/out/soong/soong.environment.used.bp2build_files Android.bp
error: external/bash/Android.bp:3:9: unrecognized property "srcs"
error: external/libncurses/Android.bp:3:9: unrecognized property "srcs"
error: external/libncurses/Android.bp:10:9: unrecognized property "srcs"
error: external/nano/Android.bp:3:9: unrecognized property "srcs"
error: external/libncurses/Android.bp:17:9: unrecognized property "srcs"
error: external/libncurses/Android.bp:24:9: unrecognized property "srcs"
error: external/libncurses/Android.bp:31:9: unrecognized property "srcs"
error: external/libncurses/Android.bp:38:9: unrecognized property "srcs"
error: external/libncurses/Android.bp:45:9: unrecognized property "srcs"
error: external/libncurses/Android.bp:52:9: unrecognized property "srcs"
error: external/libncurses/Android.bp:59:9: unrecognized property "srcs"
error: external/libncurses/Android.bp:66:9: unrecognized property "srcs"
error: external/libncurses/Android.bp:73:9: unrecognized property "srcs"
error: external/libncurses/Android.bp:80:9: unrecognized property "srcs"
error: external/libncurses/Android.bp:87:9: unrecognized property "srcs"
error: external/libncurses/Android.bp:94:9: unrecognized property "srcs"
error: external/vim/Android.bp:9:9: unrecognized property "srcs"
error: external/vim/Android.bp:18:9: unrecognized property "srcs"
error: external/vim/Android.bp:27:9: unrecognized property "srcs"
error: external/vim/Android.bp:36:9: unrecognized property "srcs"
error: external/vim/Android.bp:45:9: unrecognized property "srcs"
error: external/vim/Android.bp:54:9: unrecognized property "srcs"
error: external/vim/Android.bp:63:9: unrecognized property "srcs"                                                       12:33:52 soong bootstrap failed with: exit status 1

**Comment by samrth012** [comment]
Building for device pissarro, all other roms work fine and had a fresh sync

**Comment by Darkstar085** [comment]
This isn't superior extended tho..!! Also if it is superiorOS it isn't buildable rn..qpr2 rebase isn't done yet..

**Comment by samrth012** [comment]
> This isn't superior extended tho..!! Also if it is superiorOS it isn't buildable rn..qpr2 rebase isn't done yet..

ok cool both are not buildable getting the same error though so pinged here too

**Comment by Darkstar085** [comment]
Buildable now..

**Comment by samrth012** [comment]
> Buildable now..

Ok thanks

**Comment by samrth012** [comment]
Its built now but causing bootloop other roms work though, do u have backport stuff for 4.14 kernel ?

**Comment by Joker-V2** [comment]
Check logs and find fix

**Comment by samrth012** [comment]
No build errors sir building very fine as others roms do and as a13
superior does no errors in output just bootlooping into fastboot there is
something in different in source not sure what but till now 2 roms everest
and superior is causing the issue, a14 qpr2 cherish os lineage os,
pixelos, voltageos and many others booting just ifne.

**Comment by Darkstar085** [comment]
> Check logs and find fix

Do this

**Comment by samrth012** [comment]
> > Check logs and find fix
> 
> Do this

which logs are we talking about ?
