### ISSUE TITLE
trust hal error

### ISSUE THREAD

**Issue by baibhab34** [SuperiorOS/manifest#9]
I got this error , though i nuked trust hal from sepolicy and even tried not to build sepolicy still getting this error again and again 

libsepol.context_from_record: type hal_lineage_trust_default_exec is not defined
libsepol.context_from_record: could not create context structure
/

**Comment by Subinsmani** [comment]
Remove device/superior/sepolicy then build with permissive.

**Comment by baibhab34** [comment]
That's what i did removed sepolicy and permissive still same error

**Comment by Subinsmani** [comment]
then you remove sepolicy folder from ur device tree. 💃

**Comment by Jayant-Deshmukh** [comment]
Found the fix? Certainly prebuilt vendor I guess. Which device btw?

**Comment by Jayant-Deshmukh** [comment]
Issue is solved. You can resync.
